

POST http://localhost:8081/api-v1/product-category/add
Content-Type: application/json

{
    "category_name":"voucher"
}

###

POST http://localhost:8081/api-v1/product-category/add
Content-Type: application/json

{
    "category_name":"Songs"
}

###


POST http://localhost:8081/api-v1/product-category/add
Content-Type: application/json

{
    "category_name":"Movies"
}

###

POST http://localhost:8081/api-v1/status/add
Content-Type: application/json

{
    "status_name" : "Success"
}
###

POST http://localhost:8081/api-v1/status/add
Content-Type: application/json

{
    "status_name" : "Waiting for Payment"
}


###

POST http://localhost:8081/api-v1/status/add
Content-Type: application/json

{
    "status_name" : "Active"
}

###

POST http://localhost:8081/api-v1/unit/add
Content-Type: application/json

{
    "unit_name" : "voucher"
}

###

GET http://localhost:8081/api-v1/status/all
Content-Type: application/json

{
    "status_name" : "Waiting for Payment"
}

###
POST http://localhost:4000/api-v1/auth/login
Content-Type: application/json

{
    "email":"calvinsidik@gmail234.com",
    "password":"abcdef"
}

###
POST http://localhost:8081/api-v1/product/add
Content-Type: application/json

{
    "product_name":"Mobile Legend Bang Bang Bang",
    "product_description":"MOBA GAMES By Moon Toon",
    "category_name":"Games",
    "brand":"moon toon",
    "product_thumbnail":"https://www.stanleyulili.com/node/node-modules-import-and-use-functions-from-another-file",
    "status_name":"success",
    "published":"true"
}

###
POST http://localhost:8081/api-v1/product/add
Content-Type: application/json

{
    "product_name":"Mobile Legend Bang Bang Bang Bang2",
    "product_description":"MOBA GAMES By Moon Toon",
    "product_number":"PRD-31-132-0002",
    "category_name":"Games",
    "brand":"moon toon",
    "product_thumbnail":"https://www.stanleyulili.com/node/node-modules-import-and-use-functions-from-another-file",
    "status_name":"success",
    "published":"true"
}

###
GET http://localhost:8081/api-v1/product/all

###

POST http://localhost:8081/api-v1/currency/add
Content-Type: application/json

{
    "currency_name" : "Rupiah",
    "currency_symbol" : "Rp",
    "country" : "Indonesia"
}
###

GET http://localhost:8081/api-v1/currency/all
Content-Type: application/json


###
POST http://localhost:8081/api-v1/product-variaty/add
Content-Type: application/json

{
    "product_name" : "Mobile Legend Bang Bang Bang Bang25",
    "product_variaty_number":"VAR-3123",
    "variaty_name" : "150 Gold Coins",
    "price" : 1500,
    "unit_name" : "coins",
    "currency_name" : "Rupiah",
    "url" : "www.google.com",
    "status_name" : "active"
}

###

GET http://localhost:8081/api-v1/product-variaty/variaty-name/1/100 Gold Coins
Content-Type: application/json

###
POST http://localhost:8081/api-v1/merchant/register
Content-Type: application/json

{
    "merchant_name" : "Toko Bintang Baru",
    "merchant_tax_number" : "1230-1333-33001-000.1",
    "merchant_address" : "Jalan Jeruk Purut",
    "status_name" : "Active"
}

###
GET http://192.168.1.36:8081/api-v1/merchant/all
Content-Type:  application/json


###

POST http://localhost:8081/api-v1/transaction/create
Content-Type: application/json

{
   "user_id":1,
   "total_amount":10762,
   "product":
   [{
    "product_variaty_id":"1",
    "qty":1
   },
   {
    "product_variaty_id":"1",
    "qty":1
   }],
   "currency_name":"Rupiah"
}

###

POST http://localhost:8081/api-v1/e2p/trx/callback
Content-Type: application/json

{
    "TransId" : "A0000424172",
    "Status" : 1,
    "AuthCode" : "RB0000000"
}

###
GET http://localhost:8081/api-v1/transaction/


###
POST http://localhost:8081/api-v1/invoice/create
Content-Type: application/json

{
    "trx_id" : 2,
    "currency_name":"Rupiah"
}

###
 
 POST http://localhost:8081/api-v1/payment/request
 Content-Type: application/json

{
    "ReferenceNo" : "TRX-TEST-001",
    "TxnAmount" : "10000"
}


###
 
 POST http://localhost:8081/api-v1/payment/rePaymentRequest
 Content-Type: application/json

{
    "trx_id" : "88"
}



#  {
#       "partnerReferenceNo": "20201029000001",
#       "amount": {
#         "value": "100000.00",
#         "currency": "IDR"
#       },
#       "merchantId": "123456789",
#       "subMerchantId": "234891823",
#       "storeId": null,
#       "terminalId": "21314125",
#       "validityPeriod": "2024-05-119T22:25:100+07:00",
#       "additionalInfo": {
#         "convenienceFee": "0.00",
#         "partnerMerchantType": "SA",
#         "terminalLocationName": "Bakso Malang"
#       }
#     }

###

 POST http://localhost:8081/api-v1/product/token
 Content-Type: application/json
###


 POST http://localhost:8081/api-v1/product/voucher
 Content-Type: application/json
###


 GET http://localhost:8081/api-v1/product/id/1
 Content-Type: application/json
###

 POST http://localhost:8081/api-v1/product/games
 Content-Type: application/json
###


 POST http://localhost:8081/api-v1/product/update
 Content-Type: application/json

{
    "product_name":"Minecraft",
    "product_description":"voucher Mojang",
    "product_number":"NGQrMlloaXRnQTdIOHNobHgwV0NRSGZ0VGNoMWhsaG1kOEI2cHpMZHZXbzhYamdlUHMwN00vQXFFdlBlTkc3bG1xdThzTG9sQmR3L2xkWlZVakc4VWc9PQ==",
    "category_name":"voucher",
    "brand":"Mojang2",
    "product_thumbnail":"https://semutganteng.fra1.digitaloceanspaces.com/UniPlay/0f9d9f1404ecb25f44bf0c5ec289be60.png",
    "status":"Active",
    "published":"true"
}
###


 POST http://localhost:8081/api-v1/product/sync/uniplay/voucher
 Content-Type: application/json
###





 POST http://localhost:8081/api-v1/payment-type/create
 Content-Type: application/json

 {
    "payment":"QRIS",
    "bank" : "E2Pay",
    "account_name":"E2PAY",
    "account_number" : "21",
    "payment_fee_chrg_to_system" : "0.4",
    "payment_fee_chrg_to_customer" : "0",
    "min_amount": "10000",
    "max_amount": "9999999",
,    "timelimit_payment": "600",
    "status_name":"active"
 }
 ###





###


###


